import { DashboardContent } from "@/components/Dashboard/DashboaordContent";
import { Sidebar } from "@/components/Dashboard/Sidebar";
import { getAuthSession } from "@/lib/auth";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff", // Android Chrome
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent", // iOS Safari
    title: "My Cool App",
  },
};

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getAuthSession();

  if (!session) redirect("/login");
  return (
    <div className="min-h-screen bg-gray-50 ">
      <Sidebar />
      <DashboardContent>{children}</DashboardContent>
    </div>
  );
}
